apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgclass
spec:
  replicas: 2
  selector:
    matchLabels:
      app: imageclassifier
  template:
    metadata:
      labels:
        app: imageclassifier
    spec:
      imagePullSecrets:
        - name: gcr-creds
      containers:
      - name: cv-app
        image: europe-west1-docker.pkg.dev/cicdgcp-429910/mlops/mymlmodel:test
        ports:
        - containerPort: 8501